# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  halal:

services:

  orderer0.ageliorderer.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer0.ageliorderer.com
    container_name: orderer0.ageliorderer.com
    networks:
      - halal

  peer0.ageli.com:
    container_name: peer0.ageli.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ageli.com
    networks:
      - halal

  peer1.ageli.com:
    container_name: peer1.ageli.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.ageli.com
    networks:
      - halal

  peer0.creator.com:
    container_name: peer0.creator.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.creator.com
    networks:
      - halal

  peer1.creator.com:
    container_name: peer1.creator.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.creator.com
    networks:
      - halal

  peer0.transfer.com:
    container_name: peer0.transfer.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.transfer.com
    networks:
      - halal

  peer1.transfer.com:
    container_name: peer1.transfer.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.transfer.com
    networks:
      - halal

  peer0.seller.com:
    container_name: peer0.seller.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.seller.com
    networks:
      - halal

  peer1.seller.com:
    container_name: peer1.seller.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.seller.com
    networks:
      - halal

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.ageli.com:7051
      - CORE_PEER_LOCALMSPID=ageli
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ageli.com/peers/peer0.ageli.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ageli.com/peers/peer0.ageli.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ageli.com/peers/peer0.ageli.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ageli.com/users/Admin@ageli.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY} ${LANG}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/src/github.com:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer0.ageliorderer.com
      - peer0.ageli.com
      - peer1.ageli.com
      - peer0.creator.com
      - peer1.creator.com
      - peer0.transfer.com
      - peer1.transfer.com
      - peer0.seller.com
      - peer1.seller.com
    networks:
      - halal
